[project]
name = "pygraph"
version = "0.1.0"
description = "A re-write of pyvisjs that adds more functionality and uses a `rustworkx` backend"
license = "GPL-3.0-or-later"
license-files = ["LICENSE*"]
readme = "README.md"
authors = [
    { name = "hwelch-fle", email = "hcw360@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "rustworkx>=0.17.1",
]

[build-system]
requires = ["uv_build>=0.10.12,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
