"""Style for a GitRepo graph"""

from .models import DirectoryBuilderOpts

GitRepoStyle: DirectoryBuilderOpts = {
    'ignores': {'files': ['.gitignore'], 'patterns': ['.git/']},
    'dir_options': {'shape': 'icon', 'icon': {'code': '\uf07b'}},
    'root_options': {'icon': {'code': '\uf07b', 'color': 'gold', 'size': 100}, 'x': 0, 'y': 0, 'fixed': True},
    'file_options': {'shape': 'icon', 'icon': {'code': '\uf1c9'}},
    'file_groups': {
        '.bash': {'shape': 'icon', 'icon': {'code': '\uf120'}},
        '.c': {'shape': 'icon', 'icon': {'code': '\u0043', 'color': '#3949ab'}},
        '.cpp': {'shape': 'icon', 'icon': {'code': '\u0043', 'color': '#00589c'}},
        '.css': {'shape': 'icon', 'icon': {'code': '\ue6a2', 'color': '#006fb9'}},
        '.dockerfile': {'shape': 'icon', 'icon': {'code': '\uf395'}},
        '.go': {'shape': 'icon', 'icon': {'code': '\ue40f', 'color': '#00acd9'}},
        '.html': {'shape': 'icon', 'icon': {'code': '\uf13b', 'color': '#e44d26'}},
        '.java': {'shape': 'icon', 'icon': {'code': '\uf4e4', 'color': '#e76f01'}},
        '.jinja': {'shape': 'icon', 'icon': {'code': '\uf504'}},
        '.jpg': {'shape': 'icon', 'icon': {'code': '\uf03e'}},
        '.js': {'shape': 'icon', 'icon': {'code': '\uf3b9', 'color': '#f3832f'}},
        '.latex': {'shape': 'icon', 'icon': {'code': '\ue7ff'}},
        '.lock': {'shape': 'icon', 'icon': {'code': '\uf023', 'color': 'red'}},
        '.md': {'shape': 'icon', 'icon': {'code': '\uf60f', 'color': 'black'}},
        '.pdf': {'shape': 'icon', 'icon': {'code': '\uf1c1'}},
        '.php': {'shape': 'icon', 'icon': {'code': '\uf457', 'color': '#8a93be'}},
        '.png': {'shape': 'icon', 'icon': {'code': '\uf03e'}},
        '.py': {'shape': 'icon', 'icon': {'code': '\uf3e2', 'color': '#ffc42d'}},
        '.pyi': {'shape': 'icon', 'icon': {'code': '\uf3e2', 'color': '#357fb9'}},
        '.r': {'shape': 'icon', 'icon': {'code': '\uf4f7', 'color': '#246ac0'}},
        '.rb': {'shape': 'icon', 'icon': {'code': '\uf3a5', 'color': '#ec1d23'}},
        '.rs': {'shape': 'icon', 'icon': {'code': '\ue07a', 'color': '#e43716'}},
        '.rss': {'shape': 'icon', 'icon': {'code': '\uf143'}},
        '.sh': {'shape': 'icon', 'icon': {'code': '\uf120'}},
        '.sql': {'shape': 'icon', 'icon': {'code': '\uf1c0'}},
        '.svg': {'shape': 'icon', 'icon': {'code': '\uf55b'}},
        '.tex': {'shape': 'icon', 'icon': {'code': '\ue7ff'}},
        '.ts': {'shape': 'icon', 'icon': {'code': '\uf3b9', 'color': '#007acc'}},
        '.vue': {'shape': 'icon', 'icon': {'code': '\uf41f'}},
        '.wiki': {'shape': 'icon', 'icon': {'code': '\uf266'}},
        '.zip': {'shape': 'icon', 'icon': {'code': '\uf1c6'}},
    },
    'network_options': {
        'edges': {
            'arrows': 'to',
            'color': {'inherit': 'to', 'hover': 'gold'},
            'arrowStrikethrough': True,
            'endPointOffset': {'to': -5},
            'width': 3,
            'hoverWidth': 5,
            'length': 50,
        },
        'nodes': {
            'shadow': {
                'color': '#454545',
                'size': 3,
                'x': 1,
                'y': 1,
            },
            'font': {
                'size': 20,
                'color': '#ffffff',
                'strokeColor': '#404040',
                'strokeWidth': 3,
            },
        },
        'interaction': {
            'selectConnectedEdges': True,
            'navigationButtons': True,
            'hoverConnectedEdges': True,
            'keyboard': {'enabled': True},
        },
        'physics': {
            'solver': 'barnesHut',
            'barnesHut': {
                'avoidOverlap': 0.5,
                'centralGravity': 0.1,
                'gravitationalConstant': -15000,
                'damping': 0.05,
            },
            'maxVelocity': 50,
        },
        'configure': {
            'filter': False,
        },
    },
}
