from __future__ import annotations

from collections.abc import Callable, Hashable, Iterable, Sequence
from types import GenericAlias
from typing import TYPE_CHECKING, Any, Protocol, Self, overload, override

if TYPE_CHECKING:
    import numpy as np  # type: ignore
    import numpy.typing as npt  # type: ignore
else:
    np = object
    npt = object


__all__ = 'DiGraphProto',


type EdgeIndex = tuple[int, int]
type EdgeObject[T] = tuple[int, int, T]
type EdgeIndexMap[T] = dict[int, EdgeIndex]
type EdgeIndices = Sequence[int]
type EdgeList = Sequence[EdgeIndex]
type WeightedEdgeList[T] = Sequence[EdgeObject[T]]

type NodeIndices = Sequence[int]
type NodeMap[T] = dict[int, T]


class DiGraphProto[Node, Edge](Protocol):
    # def add_child(self, parent: int, obj: Node, edge: Edge, /) -> int: ...
    def add_edge(self, parent: int, child: int, edge: Edge, /) -> int: ...
    def add_edges_from(
        self,
        obj_list: Iterable[tuple[int, int, Edge]],
        /,
    ) -> list[int]: ...
    # def add_edges_from_no_data(
    #     self: DiGraphProto[Node, Edge | None], obj_list: Iterable[tuple[int, int]], /
    # ) -> list[int]: ...
    def add_node(self, obj: Node, /) -> int: ...
    def add_nodes_from(self, obj_list: Iterable[Node], /) -> Sequence[int]: ...
    # def add_parent(self, child: int, obj: Node, edge: Edge, /) -> int: ...
    def adj(self, node: int, /) -> dict[int, Edge]: ...
    # def adj_direction(self, node: int, direction: bool, /) -> dict[int, Edge]: ...
    def clear(self) -> None: ...
    def clear_edges(self) -> None: ...
    # def compose(
    #     self,
    #     other: DiGraphProto[Node, Edge],
    #     node_map: dict[int, tuple[int, Edge]],
    #     /,
    #     node_map_func: Callable[[Node], int] | None = ...,
    #     edge_map_func: Callable[[Edge], int] | None = ...,
    # ) -> dict[int, int]: ...
    # def contract_nodes(
    #     self,
    #     nodes: Sequence[int],
    #     obj: Node,
    #     /,
    #     check_cycle: bool | None = ...,
    #     weight_combo_fn: Callable[[Edge, Edge], Edge] | None = ...,
    # ) -> int: ...
    # def can_contract_without_cycle(self, nodes: Sequence[int], /) -> bool: ...
    def copy(self) -> Self: ...
    def edge_index_map(self) -> EdgeIndexMap[Edge]: ...
    # def edge_indices(self) -> EdgeIndices: ...
    # def edge_indices_from_endpoints(self, node_a: int, node_b: int) -> EdgeIndices: ...
    # def edge_list(self) -> EdgeList: ...
    def edges(self) -> list[Edge]: ...
    # def edge_subgraph(self, edge_list: Sequence[tuple[int, int]], /) -> DiGraphProto[Node, Edge]: ...
    # def extend_from_edge_list(
    #     self: DiGraphProto[Node | None, Edge | None], edge_list: Iterable[tuple[int, int]], /
    # ) -> None: ...
    # def extend_from_weighted_edge_list(
    #     self: DiGraphProto[Node | None, Edge],
    #     edge_list: Iterable[tuple[int, int, Edge]],
    #     /,
    # ) -> None: ...
    # def filter_edges(self, filter_function: Callable[[Edge], bool]) -> EdgeIndices: ...
    # def filter_nodes(self, filter_function: Callable[[Node], bool]) -> NodeIndices: ...
    # def find_adjacent_node_by_edge(self, node: int, predicate: Callable[[Edge], bool], /) -> Node: ...
    # def find_node_by_weight(
    #     self,
    #     obj: Node,
    #     /,
    # ) -> int | None: ...
    # def find_predecessors_by_edge(
    #     self, node: int, filter_fn: Callable[[Edge], bool], /
    # ) -> list[Node]: ...
    # def find_predecessor_node_by_edge(
    #     self, node: int, predicate: Callable[[Edge], bool], /
    # ) -> Node: ...
    # def find_successors_by_edge(
    #     self, node: int, filter_fn: Callable[[Edge], bool], /
    # ) -> list[Node]: ...
    # def find_successor_node_by_edge(self, node: int, predicate: Callable[[Edge], bool], /) -> Node: ...
    # @staticmethod
    # def from_adjacency_matrix(
    #     matrix: npt.NDArray[np.float64], /, null_value: float = ...  # type: ignore
    # ) -> DiGraphProto[int, float]: ...
    # @staticmethod
    # def from_complex_adjacency_matrix(
    #     matrix: npt.NDArray[np.complex64], /, null_value: complex = ...  # type: ignore
    # ) -> DiGraphProto[int, complex]: ...
    # def get_all_edge_data(self, node_a: int, node_b: int, /) -> list[Edge]: ...
    # def get_edge_data(self, node_a: int, node_b: int, /) -> Edge: ...
    # def get_node_data(self, node: int, /) -> Node: ...
    # def get_edge_data_by_index(self, edge_index: int, /) -> Edge: ...
    # def get_edge_endpoints_by_index(self, edge_index: int, /) -> tuple[int, int]: ...
    def has_node(self, node: int, /) -> bool: ...
    def has_edge(self, node_a: int, node_b: int, /) -> bool: ...
    def has_parallel_edges(self) -> bool: ...
    def in_degree(self, node: int, /) -> int: ...
    def in_edges(self, node: int, /) -> WeightedEdgeList[Edge]: ...
    def incident_edge_index_map(self, node: int, /, all_edges: bool = ...) -> EdgeIndexMap[Edge]: ...
    def incident_edges(self, node: int, /, all_edges: bool = ...) -> EdgeIndices: ...
    def in_edge_indices(self, node: int, /) -> EdgeIndices: ...
    def insert_node_on_in_edges(self, node: int, ref_node: int, /) -> None: ...
    def insert_node_on_in_edges_multiple(self, node: int, ref_nodes: Sequence[int], /) -> None: ...
    def insert_node_on_out_edges(self, node: int, ref_node: int, /) -> None: ...
    def insert_node_on_out_edges_multiple(self, node: int, ref_nodes: Sequence[int], /) -> None: ...
    def is_symmetric(self) -> bool: ...
    def make_symmetric(self, edge_payload_fn: Callable[[Edge], Edge] | None = ...) -> None: ...
    def merge_nodes(self, u: int, v: int, /) -> None: ...
    def neighbors(self, node: int, /) -> NodeIndices: ...
    def neighbors_undirected(self, node: int, /) -> NodeIndices: ...
    def node_indexes(self) -> NodeIndices: ...
    def node_indices(self) -> NodeIndices: ...
    def nodes(self) -> list[Node]: ...
    def num_edges(self) -> int: ...
    def num_nodes(self) -> int: ...
    def out_degree(self, node: int, /) -> int: ...
    def out_edges(self, node: int, /) -> WeightedEdgeList[Edge]: ...
    def out_edge_indices(self, node: int, /) -> EdgeIndices: ...
    def predecessor_indices(self, node: int, /) -> NodeIndices: ...
    def predecessors(self, node: int, /) -> list[Node]: ...
    @staticmethod
    def read_edge_list(
        path: str,
        /,
        comment: str | None = ...,
        deliminator: str | None = ...,
        labels: bool = ...,
    ) -> DiGraphProto[Node, Edge]: ...
    def remove_edge(self, parent: int, child: int, /) -> None: ...
    def remove_edge_from_index(self, edge: int, /) -> None: ...
    def remove_edges_from(self, index_list: Iterable[tuple[int, int]], /) -> None: ...
    def remove_node(self, node: int, /) -> None: ...
    def remove_node_retain_edges(
        self,
        node: int,
        /,
        use_outgoing: bool = ...,
        condition: Callable[[Edge, Edge], bool] | None = ...,
    ) -> None: ...
    def remove_node_retain_edges_by_id(self, node: int, /) -> None: ...
    def remove_node_retain_edges_by_key(
        self,
        node: int,
        /,
        key: Callable[[Edge], Hashable] | None = ...,
        *,
        use_outgoing: bool = ...,
    ) -> None: ...
    def remove_nodes_from(self, index_list: Iterable[int], /) -> None: ...
    # def subgraph(
    #     self, nodes: Sequence[int], /, preserve_attrs: bool = ...
    # ) -> DiGraphProto[Node, Edge]: ...
    # def subgraph_with_nodemap(
    #     self, nodes: Sequence[int], /, preserve_attrs: bool = ...
    # ) -> tuple[DiGraphProto[Node, Edge], NodeMap[int]]: ...
    # def substitute_node_with_subgraph(
    #     self,
    #     node: int,
    #     other: DiGraphProto[Node, Edge],
    #     edge_map_fn: Callable[[int, int, Edge], int | None],
    #     /,
    #     node_filter: Callable[[Node], bool] | None = ...,
    #     edge_weight_map: Callable[[Edge], Edge] | None = ...,
    # ) -> NodeMap[int]: ...
    # def successor_indices(self, node: int, /) -> NodeIndices: ...
    # def successors(self, node: int, /) -> list[Node]: ...
    @overload
    def to_dot(  # pyright: ignore[reportOverlappingOverload]
        self,
        /,
        node_attr: Callable[[Node], dict[str, str]] | None = ...,
        edge_attr: Callable[[Edge], dict[str, str]] | None = ...,
        graph_attr: dict[str, str] | None = ...,
        filename: None = ...,
    ) -> str: ...
    @overload
    def to_dot(
        self,
        /,
        node_attr: Callable[[Node], dict[str, str]] | None = ...,
        edge_attr: Callable[[Edge], dict[str, str]] | None = ...,
        graph_attr: dict[str, str] | None = ...,
        filename: str = ...,
    ) -> None: ...
    # def to_undirected(
    #     self,
    #     /,
    #     multigraph: bool = ...,
    #     weight_combo_fn: Callable[[Edge, Edge], Edge] | None = ...,
    # ) -> DiGraphProto[Node, Edge]: ...
    # def update_edge(
    #     self,
    #     source: int,
    #     target: int,
    #     edge: Edge,
    #     /,
    # ) -> None: ...
    # def update_edge_by_index(self, edge_index: int, edge: Edge, /) -> None: ...
    # def weighted_edge_list(self) -> WeightedEdgeList[Edge]: ...
    # def write_edge_list(
    #     self,
    #     path: str,
    #     /,
    #     deliminator: str | None = ...,
    #     weight_fn: Callable[[Edge], str] | None = ...,
    # ) -> None: ...
    # def reverse(self) -> None: ...
    def __delitem__(self, idx: int, /) -> None: ...
    def __getitem__(self, idx: int, /) -> Node: ...
    # @classmethod
    # def __class_getitem__(cls, key: Any, /) -> GenericAlias: ...
    # def __getnewargs_ex__(self) -> tuple[tuple[Any, ...], dict[str, Any]]: ...
    # @override
    # def __getstate__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __setitem__(self, idx: int, value: Node, /) -> None: ...
    # def __setstate__(self, state: Any, /) -> None: ...
